<a href="https://colab.research.google.com/github/Saron773/Winter-2022/blob/main/Day_5_Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Intro to Numpy

In [ ]:
import numpy as np

In [ ]:
np_city = np.array(['NYC', 'LA', 'Maimi', 'Houston'])

In [ ]:
np_city.shape

(4,)

In [ ]:
np_city.size

4

In [ ]:
np_city.dtype

dtype('<U7')

In [ ]:
np_city2 = np.array([['NYC', 'LA', 'Maimi', 'Houston'], 
                     ['NY', 'CA', 'FL', 'TX']])

In [ ]:
np_city2.shape

(2, 4)

In [ ]:
np_city2.dtype

dtype('<U7')

In [ ]:
np_city2.size

8

In [ ]:
# Create a np array with 4 lists in it... 
# each list must have 10 items in it

In [ ]:
np_numbers = np.array([['1','2','3','4','5','6','7','8','9','10'],
                      ['11','12','13','14','15','16','17','18','19','20'],
                      ['21','22','23','24','25','26','27','28','29','30'],
                      ['31','32','33','34','35','36','37','38','39','40']])

In [ ]:
np_numbers.shape

(4, 10)

In [ ]:
np_numbers.size

40

In [ ]:
first_trial_cyclist = [10, 15, 17, 26, 37, 49, 57, 61]

In [ ]:
second_trial_cyclist = [11, 45, 65, 24, 23, 45, 90, 99]

In [ ]:
np_first_trial = np.array(first_trial_cyclist)
np_second_trial = np.array(second_trial_cyclist)

In [ ]:
np_first_trial + np_second_trial

array([ 21,  60,  82,  50,  60,  94, 147, 160])

In [ ]:
np_first_trial[1] * np_second_trial[5]

675

In [ ]:
cyclist_trial = np.array([[10, 15, 17, 26],[12, 11, 21, 24]])

In [ ]:
ftrail = cyclist_trial[0]

In [ ]:
ftrail

array([10, 15, 17, 26])

In [ ]:
newlist = ['string1', 'string2']

In [ ]:
newlist[0]

'string1'

In [ ]:
newlist[0][2]

'r'

In [ ]:
test_score = np.array([[83, 71, 67, 63],[54,68,81,45]])

In [ ]:
passsed = test_score > 60

In [ ]:
passsed

array([[ True,  True,  True,  True],
       [False,  True,  True, False]])

In [ ]:
test2_scores = test_score

In [ ]:
test_score is test2_scores

True

In [43]:
test2_scores[1][3] = 78

In [44]:
test2_scores

array([[83, 71, 67, 63],
       [54, 68, 81, 78]])

In [45]:
test_score #both array values are updating cause we are making a hard copy

array([[83, 71, 67, 63],
       [54, 68, 81, 78]])

In [ ]:
NYC_Boroughs = np.array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island'])

In [ ]:
NYC_Boroughs

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island'],
      dtype='<U13')

In [ ]:
NY_Boroughs = NYC_Boroughs.view()

In [ ]:
len(NY_Boroughs)

5

In [ ]:
len(NYC_Boroughs)

5

In [ ]:
NY_Boroughs[4] = 'Central Park'

In [ ]:
NY_Boroughs

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Central Park'],
      dtype='<U13')

In [ ]:
NYC_Boroughs is NY_Boroughs #with view these two arrays aren't the same, changes made to original won't affect the other one

False

In [46]:
NYC = NYC_Boroughs.copy()

In [47]:
NYC is NYC_Boroughs

False

In [48]:
NYC[4] = 'Astoria'

In [51]:
NYC #4th element updates to Astoria

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Astoria'],
      dtype='<U13')

In [49]:
NYC_Boroughs #4th element in the array isn't changed

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Central Park'],
      dtype='<U13')